# Generated by Django 5.2.5 on 2025-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=36, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('uid', models.PositiveBigIntegerField(unique=True, verbose_name='学号')),
                ('major', models.CharField(max_length=20, verbose_name='年级专业')),
                ('phone', models.PositiveBigIntegerField(unique=True, verbose_name='手机号码')),
                ('department', models.SmallIntegerField(choices=[(0, '程序开发'), (1, 'Web开发'), (2, '游戏开发'), (3, 'APP开发'), (4, 'UI设计'), (5, 'ios')], verbose_name='意向部门')),
                ('content', models.CharField(max_length=200, verbose_name='为什么要加入爱特工作室')),
                ('status', models.SmallIntegerField(choices=[(-4, '未录取'), (-3, '二面失败'), (-2, '国庆题未完成'), (-1, '一面失败'), (0, '已报名'), (1, '一面已到'), (2, '国庆题已完成'), (3, '二面已参与'), (4, '已录取')], default=0, verbose_name='报名状态')),
                ('qq', models.PositiveBigIntegerField(unique=True, verbose_name='QQ号')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': '报名信息',
                'verbose_name_plural': '报名信息',
            },
        ),
    ]
