# Generated by Django 4.2.13 on 2024-06-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=36, unique=True, verbose_name="邮箱"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                ("major", models.CharField(max_length=20, verbose_name="年级专业")),
                (
                    "phone",
                    models.PositiveBigIntegerField(unique=True, verbose_name="手机号码"),
                ),
                (
                    "department",
                    models.SmallIntegerField(
                        choices=[
                            (0, "程序开发"),
                            (1, "Web开发"),
                            (2, "游戏开发"),
                            (3, "APP开发"),
                            (4, "UI设计"),
                        ],
                        verbose_name="意向部门",
                    ),
                ),
                (
                    "content",
                    models.CharField(max_length=200, verbose_name="为什么要加入爱特工作室"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "已报名"),
                            (1, "一审中"),
                            (2, "面试中"),
                            (3, "二审中"),
                            (4, "成功录取"),
                            (5, "一审失败"),
                            (6, "面试失败"),
                            (7, "二审失败"),
                            (8, "未录取"),
                        ],
                        default=0,
                        verbose_name="报名状态",
                    ),
                ),
                ("qq", models.PositiveBigIntegerField(null=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "报名信息",
            },
        ),
        migrations.AddField(
            model_name="verifycodemodel",
            name="send_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="verifycodemodel",
            name="email",
            field=models.EmailField(max_length=36, unique=True, verbose_name="邮箱"),
        ),
    ]
