# Generated by Django 4.2.13 on 2024-07-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0002_enrollmodel_verifycodemodel_send_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmodel",
            name="qq",
            field=models.PositiveBigIntegerField(
                null=True, unique=True, verbose_name="QQ号"
            ),
        ),
        migrations.AlterField(
            model_name="enrollmodel",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (-4, "未录取"),
                    (-3, "二审失败"),
                    (-2, "面试失败"),
                    (-1, "一审失败"),
                    (0, "已报名"),
                    (1, "一审中"),
                    (2, "面试中"),
                    (3, "二审中"),
                    (4, "成功录取"),
                ],
                default=0,
                verbose_name="报名状态",
            ),
        ),
    ]
