# Generated by Django 4.2.13 on 2024-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0003_alter_enrollmodel_qq_alter_enrollmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmodel",
            name="content",
            field=models.CharField(
                max_length=200, null=True, verbose_name="为什么要加入爱特工作室"
            ),
        ),
    ]
