# Generated by Django 4.2.13 on 2024-07-22 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0004_alter_enrollmodel_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollmodel",
            options={"verbose_name": "报名信息", "verbose_name_plural": "报名信息"},
        ),
        migrations.AlterModelOptions(
            name="verifycodemodel",
            options={"verbose_name": "验证码", "verbose_name_plural": "验证码"},
        ),
    ]
