# Generated by Django 4.2.13 on 2024-07-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0005_alter_enrollmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmodel",
            name="uid",
            field=models.PositiveBigIntegerField(
                default=1, unique=True, verbose_name="学号"
            ),
            preserve_default=False,
        ),
    ]
