# Generated by Django 3.2.20 on 2024-08-21 07:00

from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('enroll', '0006_enrollmodel_uid'),
    ]
    operations = [
        migrations.AlterField(
            model_name='enrollmodel',
            name='department',
            field=models.SmallIntegerField(
                choices=[(0, '程序开发'), (1, 'Web开发'), (2, '游戏开发'), (3, 'APP开发'), (4, 'UI设计'), (5, 'ios')],
                verbose_name='意向部门'),
            ),
    ]
