# Generated by Django 4.2.13 on 2024-08-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("enroll", "0008_verifycodemodel_comment"),
        ("enroll", "0009_remove_verifycodemodel_comment_enrollmodel_comment"),
    ]

    dependencies = [
        ("enroll", "0007_alter_enrollmodel_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmodel",
            name="comment",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
    ]
