# Generated by Django 4.2.6 on 2024-08-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_alter_enrollmodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycodemodel',
            name='comment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
