# Generated by Django 4.2.13 on 2024-09-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "enroll",
            "0008_verifycodemodel_comment_squashed_0009_remove_verifycodemodel_comment_enrollmodel_comment",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmodel",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (-4, "未录取"),
                    (-3, "二面失败"),
                    (-2, "国庆题未完成"),
                    (-1, "一面失败"),
                    (0, "已报名"),
                    (1, "一面已到"),
                    (2, "国庆题已完成"),
                    (3, "二面已参与"),
                    (4, "已录取"),
                ],
                default=0,
                verbose_name="报名状态",
            ),
        ),
    ]
