# Generated by Django 4.2.13 on 2024-09-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0010_alter_enrollmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmodel",
            name="comment",
            field=models.CharField(blank=True, max_length=64, verbose_name="备注"),
        ),
    ]
