# Generated by Django 5.2.5 on 2025-08-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_alter_enrollmodel_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifyCodeModel',
        ),
    ]
