# Generated by Django 5.2.5 on 2025-08-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('parent_message', models.TextField(blank=True, null=True, verbose_name='父评论内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('qq', models.IntegerField(null=True, verbose_name='QQ号')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='邮箱')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '已拒绝')], default=0, verbose_name='审核状态')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment', verbose_name='父评论id')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
