# Generated by Django 4.2.13 on 2024-06-01 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_time",
            new_name="datetime",
        ),
    ]
