# Generated by Django 5.2.5 on 2025-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_message',
            field=models.TextField(blank=True, null=True, verbose_name='父评论内容'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '已拒绝')], default=0, verbose_name='审核状态'),
        ),
    ]
