# Generated by Django 5.2.5 on 2025-08-31 18:39

from django.db import migrations


def populate_parent_message(apps, schema_editor):
    """为已存在的评论填充parent_message字段"""
    Comment = apps.get_model('comment', 'Comment')
    
    # 查找所有有父评论但parent_message为空的评论
    comments_with_parent = Comment.objects.filter(
        parent__isnull=False,
        parent_message__isnull=True
    )
    
    for comment in comments_with_parent:
        if comment.parent:
            comment.parent_message = comment.parent.content
            comment.save()


def reverse_populate_parent_message(apps, schema_editor):
    """回滚操作：清空parent_message字段"""
    Comment = apps.get_model('comment', 'Comment')
    Comment.objects.update(parent_message=None)


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20250901_0234'),
    ]

    operations = [
        migrations.RunPython(
            populate_parent_message,
            reverse_populate_parent_message
        ),
    ]
