# Generated by Django 4.2.6 on 2024-08-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rename_comment_time_comment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=20, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='comment',
            name='qq',
            field=models.IntegerField(null=True, verbose_name='QQ号'),
        ),
    ]
