# Generated by Django 5.2.5 on 2025-08-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '已拒绝')], default=0, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='邮箱'),
        ),
    ]
